rosa/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :artists
  end

end

rosa/app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

rosa/app/models/admin/artist.rb
class Admin::Artist < ActiveRecord::Base
end

rosa/app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < ApplicationController
  before_action :set_admin_artist, only: [:show, :edit, :update, :destroy]

  # GET /admin/artists
  # GET /admin/artists.json
  def index
    @admin_artists = Admin::Artist.all
  end

  # GET /admin/artists/1
  # GET /admin/artists/1.json
  def show
  end

  # GET /admin/artists/new
  def new
    @admin_artist = Admin::Artist.new
  end

  # GET /admin/artists/1/edit
  def edit
  end

  # POST /admin/artists
  # POST /admin/artists.json
  def create
    @admin_artist = Admin::Artist.new(admin_artist_params)

    respond_to do |format|
      if @admin_artist.save
        format.html { redirect_to @admin_artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @admin_artist }
      else
        format.html { render :new }
        format.json { render json: @admin_artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/artists/1
  # PATCH/PUT /admin/artists/1.json
  def update
    respond_to do |format|
      if @admin_artist.update(admin_artist_params)
        format.html { redirect_to @admin_artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_artist }
      else
        format.html { render :edit }
        format.json { render json: @admin_artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/artists/1
  # DELETE /admin/artists/1.json
  def destroy
    @admin_artist.destroy
    respond_to do |format|
      format.html { redirect_to admin_artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_artist
      @admin_artist = Admin::Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_artist_params
      params.require(:admin_artist).permit(:name, :sinopsis)
    end
end

rosa/app/controllers/admin_controller.rb
class AdminController < ApplicationController

	def index
		
	end
end

rosa/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rosa/app/helpers/admin/artists_helper.rb
module Admin::ArtistsHelper
end

rosa/app/helpers/admin_helper.rb
module AdminHelper
end

rosa/app/helpers/application_helper.rb
module ApplicationHelper
end

rosa/app/views/admin/artists/_form.html.erb
<%= form_for(@admin_artist) do |f| %>
  <% if @admin_artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_artist.errors.count, "error") %> prohibited this admin_artist from being saved:</h2>

      <ul>
      <% @admin_artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sinopsis %><br>
    <%= f.text_area :sinopsis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rosa/app/views/admin/artists/edit.html.erb
<h1>Editing admin_artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_artist %> |
<%= link_to 'Back', admin_artists_path %>

rosa/app/views/admin/artists/index.html.erb
<h1>Listing admin_artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sinopsis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_artists.each do |admin_artist| %>
      <tr>
        <td><%= admin_artist.name %></td>
        <td><%= admin_artist.sinopsis %></td>
        <td><%= link_to 'Show', admin_artist %></td>
        <td><%= link_to 'Edit', edit_admin_artist_path(admin_artist) %></td>
        <td><%= link_to 'Destroy', admin_artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_admin_artist_path %>

rosa/app/views/admin/artists/new.html.erb
<h1>New admin_artist</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_artists_path %>

rosa/app/views/admin/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_artist.name %>
</p>

<p>
  <strong>Sinopsis:</strong>
  <%= @admin_artist.sinopsis %>
</p>

<%= link_to 'Edit', edit_admin_artist_path(@admin_artist) %> |
<%= link_to 'Back', admin_artists_path %>

rosa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rosa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>